name: 构建并推送 Docker 镜像

on:
  push:
    tags:
      - 'v*.*'  # 匹配所有类似 v1.0, v2.1 等的标签
  workflow_dispatch:  # 保留手动触发选项

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mastodon-bluesky-sync

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 提取版本号
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: 设置 GHCR 镜像名称
      run: echo "GHCR_IMAGE_NAME=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/mastodon-bluesky-sync" >> $GITHUB_ENV

    - name: 登录到 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 登录到 GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 构建并推送 Docker 镜像
      uses: docker/build-push-action@v4
      id: docker_build
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          ${{ env.GHCR_IMAGE_NAME }}:latest
          ${{ env.GHCR_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

    - name: 镜像摘要
      run: echo ${{ steps.docker_build.outputs.digest }}
